# 大会向け
# マッチオプティマイザの設定を必要に応じて変更してください

server:
  web_socket:
    host: "127.0.0.1" # ホスト名
    port: 8080 # ポート番号
  self_match: true # 同じチーム名のエージェント同士のみをマッチングさせるか

game:
  agent_count: 5 # 1ゲームあたりのエージェント数
  vote_visibility: false # 投票の結果を公開するか
  talk_on_first_day: true # 1日目の発言を許可するか
  max_continue_error_ratio: 0.2 # ゲームを継続するエラーエージェントの最大割合
  talk:
    max_count:
      per_agent: 5 # 1日あたりの1エージェントの最大発言回数
      per_day: 20 # 1日あたりの全体の発言回数
  whisper:
    max_count:
      per_agent: 5 # 1日あたりの1エージェントの最大囁き回数
      per_day: 20 # 1日あたりの全体の囁き回数
  skip:
    max_count: 0 # 1日あたりの1エージェントの最大スキップ回数
  vote:
    max_count: 1 # 1位タイの場合の最大再投票回数
  attack:
    max_count: 1 # 1位タイの場合の最大襲撃再投票回数
    allow_no_target: false # 襲撃なしの日を許可するか
  timeout:
    action: 60s # エージェントのアクションのタイムアウト時間
    response: 120s # エージェントの生存確認のタイムアウト時間

analysis_service:
  enable: true # 分析サービスを有効にするか
  output_dir: "./log" # 分析結果の出力ディレクトリ
  filename: "{timestamp}_{teams}" # 分析結果のファイル名

api_service:
  enable: true # APIサービスを有効にするか
  publish_running_game: true # 進行中のゲームを公開するか

deprecated_log_service:
  enable: true # 従来形式のログ出力サービスを有効にするか
  output_dir: "./log" # ログの出力ディレクトリ
  filename: "{timestamp}_{teams}" # ログのファイル名

match_optimizer:
  enable: false # マッチオプティマイザを有効にするか
  team_count: 5 # 参加するチーム数
  game_count: 30 # 全体のゲーム数
  output_path: "./log/match_optimizer.json" # マッチ履歴の出力ファイル
  infinite_loop: false # スケジュールされたマッチがすべて終了した場合に全体のゲーム数分のゲームを追加するか
